# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server.

# Site settings
title: Victor Zo Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog where I share thoughts on technology, 
  development, and life experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://victor-zo-blog.io" # the base hostname & protocol for your site

twitter_username: victorzo
github_username: victorzo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minima theme customization
minima:
  skin: dark

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - logs/