{
 "title": "Cilium Metrics",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "tags": [
  "cilium",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(cilium_version,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, level) * 60",
     "legendFormat": "{{level}} {{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage per node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node) * 100",
     "legendFormat": "min {{node}}"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node) * 100",
     "legendFormat": "avg {{node}}"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node) * 100",
     "legendFormat": "max {{node}}"
    }
   ]
  },
  {
   "title": "Generic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "Min Virtual Memory"
    },
    {
     "expr": "avg(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "Average Virtual Memory"
    },
    {
     "expr": "max(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "Max Virtual Memory"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_process_open_fds{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "all nodes"
    },
    {
     "expr": "min(cilium_process_open_fds{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "min/node"
    },
    {
     "expr": "avg(cilium_process_open_fds{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "avg/node"
    },
    {
     "expr": "max(cilium_process_open_fds{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "max/node"
    }
   ]
  },
  {
   "title": "System-wide BPF memory usage",
   "type": "timeseries",
   "description": "BPF memory usage in the entire system including components not managed by Cilium.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\", node=~\"$node\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "AVG_bpf_memory_bytes_avg"
    },
    {
     "expr": "max(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\", node=~\"$node\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "MAX_bpf_memory_bytes_max"
    },
    {
     "expr": "min(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\", node=~\"$node\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\", node=~\"$node\"})",
     "legendFormat": "MIN_bpf_memory_bytes_min"
    }
   ]
  },
  {
   "title": "BPF map pressure",
   "type": "timeseries",
   "description": "Fill percentage of BPF maps, tagged by map name",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cilium_bpf_map_pressure{k8s_app=\"cilium\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API call latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "API call latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "# API calls (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "# API calls (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "API return codes (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} {{node}} )"
    }
   ]
  },
  {
   "title": "API return codes (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} {{node}} )"
    }
   ]
  },
  {
   "title": "Cilium",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "BPF",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "map ops (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}} {{node}}"
    }
   ]
  },
  {
   "title": "map ops (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}} {{node}}"
    }
   ]
  },
  {
   "title": "map ops (sum failures)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\",outcome=\"fail\", node=~\"$node\"}[5m])) by (node, map_name, operation)",
     "legendFormat": "{{map_name}} {{operation}} {{node}}"
    }
   ]
  },
  {
   "title": "kvstore",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_kvstore_operations_duration_seconds_sum{node=~\"$node\"}[5m])) by (node, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{node=~\"$node\"}[5m])) by (node, action, scope))",
     "legendFormat": "{{action}} {{scope}} {{node}}"
    }
   ]
  },
  {
   "title": "latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_kvstore_operations_duration_seconds_sum{node=~\"$node\"}[5m])) by (node, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{node=~\"$node\"}[5m])) by (node, action, scope))",
     "legendFormat": "{{action}} {{scope}} {{node}}"
    }
   ]
  },
  {
   "title": "Events received (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{node=~\"$node\"}[5m])) by (node, scope, action)",
     "legendFormat": "{{action}} {{scope}} {{node}}"
    }
   ]
  },
  {
   "title": "Cilium network information",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Forwarded Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_count_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, direction)",
     "legendFormat": "{{direction}} {{node}}"
    }
   ]
  },
  {
   "title": "Forwarded Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, direction) * 8",
     "legendFormat": "{{direction}} {{node}}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack Non-TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack Non-TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", node=~\"$node\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "Allocated Addresses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{k8s_app=\"cilium\", node=~\"$node\"}) by (node, family)\n",
     "legendFormat": "{{family}} {{node}}"
    }
   ]
  },
  {
   "title": "Datapath Conntrack Dump Resets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_dump_resets_total{k8s_app=\"cilium\", node=~\"$node\"}) by (node, area, family, name)",
     "legendFormat": "{{name}} {{area}} {{family}} {{node}}"
    }
   ]
  },
  {
   "title": "Service Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_services_events_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, action)",
     "legendFormat": "{{action}} {{node}}"
    }
   ]
  },
  {
   "title": "Connectivity Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_unreachable_nodes{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "unreachable nodes {{node}}"
    },
    {
     "expr": "sum(cilium_unreachable_health_endpoints{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "unreachable health endpoints {{node}}"
    }
   ]
  },
  {
   "title": "Dropped Egress Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"EGRESS\", k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_nodes_all_events_received_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, event_type, source) * 60",
     "legendFormat": "{{eventType}} {{source}} {{node}}"
    }
   ]
  },
  {
   "title": "Dropped Egress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"EGRESS\", k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cilium_nodes_all_num{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "Average Nodes {{node}}"
    },
    {
     "expr": "min(cilium_nodes_all_num{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "Min Nodes {{node}}"
    },
    {
     "expr": "max(cilium_nodes_all_num{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "Max Nodes {{node}}"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "L7 forwarded request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_total{k8s_app=\"cilium\", node=~\"$node\", rule=\"denied\"}[5m]))",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_total{k8s_app=\"cilium\", node=~\"$node\", rule=\"forwarded\"}[5m]))",
     "legendFormat": "forwarded"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_total{k8s_app=\"cilium\", node=~\"$node\", rule=\"received\"}[5m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Cilium drops Ingress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Proxy response time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[1m])) by (node, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[1m])) by (node, scope)",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg(cilium_policy_l7_total{k8s_app=\"cilium\", node=~\"$node\", rule=\"parse_errors\"}) by (node)",
     "legendFormat": "parse errors {{node}}"
    }
   ]
  },
  {
   "title": "Dropped Ingress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\", k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Proxy response time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_proxy_upstream_reply_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, scope)",
     "legendFormat": "Max {{scope}}"
    },
    {
     "expr": "max(rate(cilium_policy_l7_total{k8s_app=\"cilium\", node=~\"$node\", rule=\"parse_errors\"}[5m])) by (node)",
     "legendFormat": "parse errors {{node}}"
    }
   ]
  },
  {
   "title": "Endpoints policy enforcement status",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(cilium_policy_endpoint_enforcement_status{k8s_app=\"cilium\", node=~\"$node\"}) by (enforcement)",
     "legendFormat": "{{enforcement}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Runs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node) * 60",
     "legendFormat": "min trigger {{node}}"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node) * 60",
     "legendFormat": "average trigger"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\", pod=~\"$pod\"}[5m])) by (pod) * 60",
     "legendFormat": "max trigger {{node}}"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_folds{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node) * 60",
     "legendFormat": "folds {{node}}"
    }
   ]
  },
  {
   "title": "Policies Per Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_policy{k8s_app=\"cilium\", node=~\"$node\"}) by(node)",
     "legendFormat": "min {{node}}"
    },
    {
     "expr": "avg(cilium_policy{k8s_app=\"cilium\", node=~\"$node\"}) by(node)",
     "legendFormat": "avg {{node}}"
    },
    {
     "expr": "max(cilium_policy{k8s_app=\"cilium\", node=~\"$node\"}) by(node)",
     "legendFormat": "max {{node}}"
    },
    {
     "expr": "sum(cilium_policy_change_total{k8s_app=\"cilium\", node=~\"$node\", outcome=\"failure\"}) by (node)",
     "legendFormat": "policy change errors {{node}}"
    }
   ]
  },
  {
   "title": "Policy Revision",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_policy_max_revision{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "min {{node}}"
    },
    {
     "expr": "avg(cilium_policy_max_revision{k8s_app=\"cilium\", node=~\"$node\"}) by (node)",
     "legendFormat": "avg {{node}}"
    },
    {
     "expr": "max(cilium_policy_max_revision{k8s_app=\"cilium\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "max {{node}}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint regeneration time (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\", node=~\"$node\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!~\"total\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{k8s_app=\"cilium\", node=~\"$node\"}) by (endpoint_state)",
     "legendFormat": "{{endpoint_state}}"
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Controllers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node)",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(cilium_controllers_failing{k8s_app=\"cilium\", pod=~\"$pod\"}) by(pod)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Controller Durations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_duration_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, status) / sum(rate(cilium_controllers_runs_duration_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes integration",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {}
   ]
  },
  {
   "title": "apiserver latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_k8s_client_api_latency_time_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])/rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "apiserver latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_k8s_client_api_latency_time_seconds_sum{k8s_app=\"cilium\", node=~\"$node\"}[5m])/rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "apiserver #calls (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, path)",
     "legendFormat": "{{method}} {{path}} {{node}}"
    }
   ]
  },
  {
   "title": "apiserver calls (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_calls_total{k8s_app=\"cilium\", node=~\"$node\"}[5m])) by (node, method, return_code)",
     "legendFormat": "{{method}} {{return_code}} {{node}}"
    }
   ]
  },
  {
   "title": "Valid, Unnecessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"true\", node=~\"$node\"}[5m])) by (node, scope, action)",
     "legendFormat": "{{action}} {{scope}} {{node}}"
    }
   ]
  },
  {
   "title": "Invalid, Unnecessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"false\", node=~\"$node\"}[5m])) by (node, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Valid, Necessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"true\", node=~\"$node\"}[5m])) by (node, scope, action, valid)",
     "legendFormat": "{{action}} {{scope}} {{node}}"
    }
   ]
  },
  {
   "title": "Invalid, Necessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"false\", node=~\"$node\"}[5m])) by (node, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "CiliumNetworkPolicy Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"CiliumNetworkPolicy\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "NetworkPolicy Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"CiliumNetworkPolicy\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Pod\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} avg {{node}}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Node\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} avg {{node}}"
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Service\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} {{node}}"
    }
   ]
  },
  {
   "title": "Endpoints Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Endpoint\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} {{node}}"
    }
   ]
  },
  {
   "title": "Namespace Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Namespace\", node=~\"$node\"}[5m])) by (node, action) * 60",
     "legendFormat": "{{action}} {{node}}"
    }
   ]
  }
 ]
}